services:
  - type: web
    name: bookstore-api
    env: node
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://cloud1:<25M7BoXmjchSE2Xi>@cluster0.3jm9f.mongodb.net/

  - type: web
    name: bookstore-client
    env: static
    buildCommand: echo "no build"
    staticPublishPath: client
